### ISSUE TITLE
should-not-typecheck-2.0 broken by HUnit update

### ISSUE THREAD

**Issue by peti** [CRogers/should-not-typecheck#3]
Please see http://hydra.cryp.to/build/1144556/log/raw for a complete build log.

**Comment by CRogers** [comment]
Thanks for the bug report! Will take a look when I'm free.

**Comment by CRogers** [comment]
a7f38d3 should fix this. Travis is being slow but once the build goes green I'll make a Hackage release.

**Comment by CRogers** [comment]
Fixed with 2.0.1 release on Hackage: https://hackage.haskell.org/package/should-not-typecheck-2.0.1
